### ISSUE TITLE
Logo Proposal: Auto-mute

### ISSUE THREAD

**Issue by baranpirincal** [sommd/auto-mute#3]
Hey! I think that your logo design is little bit generic. I can contribute on your project with making logo design. What do you think about re-designing logo of Auto-mute? Actually, my goal is make my portfolio better with supporting open-source projects. I am waiting your feedback, have a nice day!

Best Regards
Baran Pirinçal
Graphic Designer

**Comment by sommd** [comment]
If you'd like to design a logo, that would be awesome. The current one was just made from a stock Material icon in 5 minutes.

If you do make an icon, an [adaptive icon](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive) would be preferred. Basically it's just a foreground and background layers, both 108x108dp with the content in the inner 72x72dp. The [Material Design guidelines](https://material.io/design/iconography/) might also be useful, but you don't have to follow them exactly.

You can just open a pull request with the Illustrator or SVG file and I'll add it to the app.

**Comment by baranpirincal** [comment]
@sommd Hey again! I made my first experiments. I hope you like it. If you want to add or remove something on design I can do it. Please feel free about criticize. Have a nice day!

![automute](https://user-images.githubusercontent.com/37786733/40998322-1f690096-6910-11e8-9407-728724663bd4.jpg)

**Comment by baranpirincal** [comment]
If you want it we can delete the mouth idea, I am not sure about that. Is it fit to your project or not

**Comment by baranpirincal** [comment]
![automute2](https://user-images.githubusercontent.com/37786733/41004191-b1c0ecb8-6921-11e8-92dd-fbd5837e35cd.jpg)

**Comment by sommd** [comment]
Thanks. These look good. I agree about the mouth idea, I think it's better without it.

I like the second alternative with the blue-purple gradient, maybe with different colours though? I feel that the sound icon is a bit too cartoon-ish, maybe make it less rounded and more angular. Could you also try making the stroke a bit thinner, and remove the gap between the sound icon and the "mute" line?

**Comment by baranpirincal** [comment]
Hey again, I tried again according to your feedbacks. Could you please check it? Have a nice day! :)

![dd](https://user-images.githubusercontent.com/37786733/41187832-893c19b0-6bbb-11e8-8d8f-53ddb889ef31.png)

**Comment by baranpirincal** [comment]
@sommd I am waiting your feedback! :)

**Comment by sommd** [comment]
Thanks for designing these, but I think I might be a bit too attached to the current icon. I think your skills would be better spent on other projects since I'm not too concerned about marketing or branding. This project is mainly for personal use, so I don't mind if the logo doesn't attract any users. Feel free to put these designs in your portfolio if you want, they are yours after all.

As for feedback (if you want it): I'm still not sure how I feel about the sound icon, it seems a bit too robotic. The volume knob idea is good but I think it stands out too much with the stroke, maybe having it flush with the line would look nicer? Overall I don't think the icon fits in well with other Android icons, but I like your ideas.

**Comment by baranpirincal** [comment]
Hum :( Np, thanks for all of your comments and feedbacks! Have a nice day :)
