### ISSUE TITLE
[Feature request] Ignore apps (white noise)

### ISSUE THREAD

**Issue by JanWaldhorn** [sommd/auto-mute#7]
I use [EasyNoise ](https://github.com/cliambrown/EasyNoise)and every now and then (especially with the app in the background) the volume gets minimized by AutoMute, even though the sound is supposed to continue.
I guess it would be easiest if EasyNoise or another app would not experience AutoMute as "Opt-Out" in the settings.

**Comment by sommd** [comment]
Hmm, it seems like Easy Noise uses a [`SoundPool`](https://developer.android.com/reference/android/media/SoundPool) to play its audio which for some reason isn't being detected by Auto Mute, so Auto Mute thinks there's no audio playing. I'll try to look into it when I next have time but this may be a bug in Android if `SoundPool` doesn't trigger [the API](https://developer.android.com/reference/android/media/AudioManager#registerAudioPlaybackCallback(android.media.AudioManager.AudioPlaybackCallback,%20android.os.Handler)) that Auto Mute uses to detect audio playback.

**Comment by sommd** [comment]
Yeah, seems like `SoundPool` doesn't trigger `AudioPlaybackCallback` so there's no way for Auto Mute to detect that audio is playing. This is probably an Android bug so there's nothing that can be done unfortunately. :cry:

As a workaround you could disable the Auto Mute service when you want to use Easy Noise and re-enabled it after. Auto Mute provides a quick settings tile you can add which will make this a bit more convenient, but I know it's still not ideal sorry.

Auto Mute can't detect which app audio is coming from since Android doesn't provide this, so implementing any kind of per-app detection (as the title of this issue suggests) isn't possible either, so I'm going to close this issue.
